/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AuthUsers: () => import('#controllers/auth_users_controller'),
  Authors: () => import('#controllers/authors_controller'),
  Books: () => import('#controllers/books_controller'),
  Loans: () => import('#controllers/loans_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
}
